# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f515f6e08e36480afdc0757a90cd58497d902c6f6f1e6d7a10a26caebae8a6d2c691bf1fb08a6bbfc2572e8ce93e4fe54db95e07195c7f1ce4639dbbcc1c93c

test:
  secret_key_base: 7a699de2c8bdff5f2e254a0bd4c2c2606f1617c16901bf19bbd94e69edbd7117fa189bab403d2ad98abec52e108f7c59e4300e5fb500797b9fd7397131b2196f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
